version: '3.1'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_ROOT_PASSWORD: dlqhfka
      MYSQL_DATABASE: sseg
      MYSQL_USER: sechan
      MYSQL_PASSWORD: dlqhfka
    ports:
      - "3307:3306"
    volumes:
      - mysql_volume:/var/lib/mysql

  sseg-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - mysql
      - redis

volumes:
  mysql_volume:
