server:
  port: 80

  redis:
    host: localhost
    port: 6379

spring:
  config:
    activate:
      on-profile: dev

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sseg

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/google'

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  devtools:
    livereload:
      enabled: true


custom:
  email:
    from:
      email-verification: verify@sseg.io
  site:
    name: sseg
    login-form-url: /login
    base-url: 'http://sseg.seryinf.com:${server.port}'
  admin:
    contact-email: sechan100@gmail.com