spring:
  security:
    oauth2:
      client:
        registration:
          naver:
            clientId: vgKyrDOYWFCBZlFdinRr
            client-secret: _UeR_OnwNR
          google:
            clientId: 1097482323285-ouhem2cuav1alpsu48js4tnpf6lh3dt7.apps.googleusercontent.com
            client-secret: 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
