server:
  port: 80

spring:
  config:
    activate:
      on-profile: prod

  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  redis:
    host: localhost
    port: 6379

  datasource:
    username: admin
    password: Mnnzxc2004!
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://sseg.c8j6g3p9mdgp.ap-northeast-2.rds.amazonaws.com:3306/sseg

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/google'

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


custom:
  email:
    from:
      email-verification: verify@sseg.io
  site:
    name: sseg
    login-form-url: /login
    base-url: 'http://sseg.seryinf.com:${server.port}'
  admin:
    contact-email: sechan100@gmail.com