server:
  port: 8080

jwt:
  expirationPeriodMinutes: 30
  refresh:
    expirationPeriodDay: 14


spring:
  profiles:
    active: smtp
    include:
      - secret
      - custom

  jackson:
    default-property-inclusion: non_null

  redis:
    host: localhost
    port: 6379

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sseg

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  security:
    oauth2:
      client:
        registration:

          naver:
            scope: profile,email
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/naver'

          google:
            scope: profile, email
            client-name: google
            authorization-grant-type: authorization_code
            redirect-uri: '${custom.site.base-url}/login/oauth2/code/google'

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG