jwt:
  expirationPeriodMinutes: 30
  refresh:
    expirationPeriodDay: 14


spring:
  profiles:
    active: dev
    include:
      - secret

  jackson:
    default-property-inclusion: non_null

  output:
    ansi:
      enabled: always

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG