custom:

  email:
    from:
      email-verification: verify@sseg.io

  site:
    name: sseg
    login-form-url: /login
    base-url: 'http://localhost:${server.port}'

  admin:
    contact-email: sechan100@gmail.com