server:
  port: 8080

spring:
  profiles:
    active: smtp

  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: classpath:templates
    suffix: .html

  datasource:
    username: root
    password: dlqhfka
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sseg

  jpa:
    hibernate:
      ddl-auto: create
      properties:
        hibernate:
          user_sql_comments: true
          format_sql: true
          show_sql: true

  output:
    ansi:
      enabled: always

  devtools:
    livereload:
      enabled: true
  freemarker:
    :ache: false